### ISSUE TITLE
Differences between `statesman` and `simpy`?

### ISSUE THREAD

**Issue by FanwangM** [opsani/statesman#111]
Thank you for developing the nice package.

Can you elaborate on the differences between `statesman` and `simpy`?  As far as I know, both work for discrete event simulations.

Thank you.
@blakewatters @linkous8

**Comment by linkous8** [comment]
@FanwangM unfortunately I don't really have an answer for you. I've only been conducting barebones maintenance on this repo to support its use in another code base both of which fell onto my plate when Blake left our organization.

If evaluating which one to use, `simpy` is probably a more mature solution.

**Comment by FanwangM** [comment]
Thank you very much!
@linkous8
