### ISSUE TITLE
Synchronous API?

### ISSUE THREAD

**Issue by hongquan** [opsani/statesman#15]
I have just found statesman. It looks great. Being typed, using enum instead of strings are what I'm looking for. But the requirement of `await` make it difficult to integrate to my app. Do you plan to support synchronous API?

I want to use `statesman` in a GTK app. Many operations are asynchronous, but using GTK main loop instead of Python asyncio event loop.

**Comment by blakewatters** [comment]
You can try wrapping it with a `concurrent.futures.ThreadPoolExecutor` or something but this is a tough one because one of the key design points is being async and integrated with asyncio.

You are gonna have to figure this one out on your own homie
